name: CI - DEV
on:
  push:
    branches:
      - 'ROBO-**'
jobs:
  Build:
    uses: nareshgdevops/roboshop-github-actions/.github/workflows/CI-DEV.yml@main
    with:
      appType: maven
      appName: shipping
    secrets:
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}