name: Docker Build - DB Load
on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: http://vault-int.nareshdevops1218.online:8200/
          token: ${{ secrets.vault_token }}
          secrets: |
            roboshop-infra/data/azure-service-priniciple AZURE_SUBSCRIPTION_ID | AZURE_SUBSCRIPTION_ID ;
            roboshop-infra/data/azure-service-priniciple AZURE_CLIENT_ID | AZURE_CLIENT_ID ;
            roboshop-infra/data/azure-service-priniciple AZURE_SECRET | AZURE_SECRET ;
            roboshop-infra/data/azure-service-priniciple AZURE_TENANT | AZURE_TENANT ;

      - name: Docker Build
        run: |
          az login --service-principal --username $AZURE_CLIENT_ID --password $AZURE_SECRET --tenant $AZURE_TENANT
          az acr login --name nareshgdevops
          docker build -t nareshgdevops.azurecr.io/roboshop-shipping-db-job:latest -f Dockerfile-dbjob .
          docker push nareshgdevops.azurecr.io/roboshop-shipping-db-job:latest